def god():
    god_quotes = [
    {"quote": "God's timing is always perfect."},
    {"quote": "Pray first, worry less."},
    {"quote": "With God, all things are possible."},
    {"quote": "Faith can move mountains."},
    {"quote": "God never leaves you alone."},
    {"quote": "Trust God even when you don't understand."},
    {"quote": "God's plan is greater than your fear."},
    {"quote": "Grace changes everything."},
    {"quote": "God is working behind the scenes."},
    {"quote": "When you are weak, God is strong."},
    {"quote": "God opens doors no one can shut."},
    {"quote": "Peace begins with prayer."},
    {"quote": "God's love never fails."},
    {"quote": "Faith over fear."},
    {"quote": "God knows your heart."},
    {"quote": "Every day is a gift from God."},
    {"quote": "God's mercy is new every morning."},
    {"quote": "Stay patient, God is preparing something."},
    {"quote": "God sees every silent prayer."},
    {"quote": "Hope in God brings strength."},
    {"quote": "God's promises never expire."},
    {"quote": "Walk by faith, not by sight."},
    {"quote": "God turns pain into purpose."},
    {"quote": "Prayer is power."},
    {"quote": "God is bigger than every problem."},
    {"quote": "Blessings come through trust."},
    {"quote": "God hears every whisper."},
    {"quote": "Faith grows in hard seasons."},
    {"quote": "God's light shines in darkness."},
    {"quote": "Keep going, God is with you."},
    {"quote": "God gives strength for today."},
    {"quote": "Trust the path God prepares."},
    {"quote": "God can calm every storm."},
    {"quote": "Prayer changes the atmosphere."},
    {"quote": "God's grace is enough."},
    {"quote": "Faith unlocks courage."},
    {"quote": "God is near to the brokenhearted."},
    {"quote": "Nothing surprises God."},
    {"quote": "God provides in the right season."},
    {"quote": "Faith grows through waiting."},
    {"quote": "God writes better stories."},
    {"quote": "Prayer brings peace to chaos."},
    {"quote": "God restores what was lost."},
    {"quote": "His love remains constant."},
    {"quote": "God can use every setback."},
    {"quote": "Faith keeps moving forward."},
    {"quote": "God sees what others miss."},
    {"quote": "Mercy meets you each morning."},
    {"quote": "God's power works in weakness."},
    {"quote": "Keep trusting, God is faithful."}
]
    return god_quotes
