def healing():

    healing_quotes = [
    {"quote": "Healing takes time, and that is okay."},
    {"quote": "Small progress is still healing."},
    {"quote": "Rest is part of healing."},
    {"quote": "You do not have to rush recovery."},
    {"quote": "Every day can bring new strength."},
    {"quote": "Healing begins with patience."},
    {"quote": "Your scars show survival, not weakness."},
    {"quote": "Peace grows where pain once lived."},
    {"quote": "Step by step, you are healing."},
    {"quote": "Even slow healing is healing."},
    {"quote": "Be gentle with yourself today."},
    {"quote": "Growth often starts after pain."},
    {"quote": "Healing is not always linear."},
    {"quote": "Give yourself grace while you heal."},
    {"quote": "Some wounds need kindness, not pressure."},
    {"quote": "You are stronger than yesterday."},
    {"quote": "Healing happens quietly too."},
    {"quote": "Hope is medicine for the heart."},
    {"quote": "Better days are being built now."},
    {"quote": "Recovery is progress, not perfection."},
    {"quote": "You deserve peace and healing."},
    {"quote": "Take the next small step."},
    {"quote": "Your heart can heal again."},
    {"quote": "Pain can pass, strength can stay."},
    {"quote": "Healing starts when you keep going."},
    {"quote": "Breathe deeply, heal slowly."},
    {"quote": "You are allowed to rest."},
    {"quote": "Sunlight returns after storms."},
    {"quote": "Healing is courage in quiet form."},
    {"quote": "You are becoming whole again."},
    {"quote": "Time can soften heavy pain."},
    {"quote": "Healing begins with one calm breath."},
    {"quote": "You are allowed to start over."},
    {"quote": "Peace returns little by little."},
    {"quote": "Your story is still unfolding."},
    {"quote": "Healing grows through patience and care."},
    {"quote": "Some days resting is progress."},
    {"quote": "Strength returns in quiet moments."},
    {"quote": "You can heal without rushing."},
    {"quote": "Each sunrise brings new hope."},
    {"quote": "Gentle steps still move forward."},
    {"quote": "Healing honors your courage."},
    {"quote": "You are rebuilding from within."},
    {"quote": "Scars can become symbols of strength."},
    {"quote": "Your heart knows how to mend."},
    {"quote": "Healing welcomes slow progress."},
    {"quote": "Today can be lighter than yesterday."},
    {"quote": "Kindness to yourself is medicine."},
    {"quote": "Even now, healing is happening."},
    {"quote": "You are growing through recovery."}
]

    return healing_quotes
