def motivation():
    motivational_quotes = [
    {"quotes" : "Never Give up"},
    {"quotes": "Start now, improve daily."},
    {"quotes": "Discipline beats motivation."},
    {"quotes": "Small steps create big results."},
    {"quotes": "Consistency builds greatness."},
    {"quotes": "Dream big, work bigger."},
    {"quotes": "Focus on progress, not perfection."},
    {"quotes": "Hard days build strong minds."},
    {"quotes": "Winners keep showing up."},
    {"quotes": "Your future needs today's effort."},
    {"quotes": "Success loves persistence."},
    {"quotes": "Do it scared, but do it."},
    {"quotes": "One hour today changes tomorrow."},
    {"quotes": "Stay hungry for growth."},
    {"quotes": "Excuses delay success."},
    {"quotes": "Be stronger than your mood."},
    {"quotes": "Skill grows through repetition."},
    {"quotes": "Pressure creates diamonds."},
    {"quotes": "Keep moving, even slowly."},
    {"quotes": "Effort compounds over time."},
    {"quotes": "Make yourself proud."},
    {"quotes": "Build habits, not wishes."},
    {"quotes": "Pain of work beats regret."},
    {"quotes": "You can begin again today."},
    {"quotes": "Confidence comes from action."},
    {"quotes": "Learn, build, repeat."},
    {"quotes": "Doubt dies when work begins."},
    {"quotes": "The grind reveals character."},
    {"quotes": "Stay patient and relentless."},
    {"quotes": "Action defeats fear."},
    {"quotes": "Do more than you planned."},
    {"quotes": "Progress is earned daily."},
    {"quotes": "Strong minds finish tasks."},
    {"quotes": "Greatness hides in routines."},
    {"quotes": "Results respect consistency."},
    {"quotes": "Push past average."},
    {"quotes": "Work while others wait."},
    {"quotes": "Make discipline your advantage."},
    {"quotes": "Start messy, finish strong."},
    {"quotes": "Success begins with one move."},
    {"quotes": "Stay focused, stay dangerous."},
    {"quotes": "Turn setbacks into fuel."},
    {"quotes": "Earn your confidence."},
    {"quotes": "Your habits shape destiny."},
    {"quotes": "Growth requires discomfort."},
    {"quotes": "Rise again every time."},
    {"quotes": "Keep promises to yourself."},
    {"quotes": "Become hard to stop."},
    {"quotes": "The work always shows."},
    {"quotes": "Today is your chance."}
    ]

    
    return motivational_quotes
