def training():
    #--------------------------------++ intents = god, motivation, heeling, money ++----------------------------------------------
    data = [
    ("How can I earn money online", "money"),
    ("I need ideas to make money", "money"),
    ("How do I become rich", "money"),
    ("Ways to earn passive income", "money"),
    ("How to start a business", "money"),
    ("I want financial freedom", "money"),
    ("Best side hustles for students", "money"),
    ("How to save money effectively", "money"),
    ("I want to make more income", "money"),
    ("How do people get wealthy", "money"),
    ("I feel like giving up", "motivation"),
    ("Give me motivation to work", "motivation"),
    ("I am feeling lazy today", "motivation"),
    ("How to stay disciplined", "motivation"),
    ("I need motivation to study", "motivation"),
    ("I have no energy to work", "motivation"),
    ("How to stay consistent", "motivation"),
    ("I keep procrastinating", "motivation"),
    ("Push me to work harder", "motivation"),
    ("I want to improve myself", "motivation"),
    ("I feel sad and broken", "healing"),
    ("How to heal from pain", "healing"),
    ("I am emotionally hurt", "healing"),
    ("I feel lonely", "healing"),
    ("How to deal with stress", "healing"),
    ("I feel anxious", "healing"),
    ("I am overthinking everything", "healing"),
    ("How to calm my mind", "healing"),
    ("I feel empty inside", "healing"),
    ("Help me heal emotionally", "healing"),
    ("I want to get closer to God", "god"),
    ("How to pray properly", "god"),
    ("Teach me about God", "god"),
    ("I want spiritual guidance", "god"),
    ("How to build faith", "god"),
    ("I feel disconnected from God", "god"),
    ("Guide me spiritually", "god"),
    ("What does God want from me", "god"),
    ("How to trust God", "god"),
    ("I want to grow spiritually", "god"),
    ("I need money urgently", "money"),
    ("How to earn money as a teen", "money"),
    ("Ways to make money without investment", "money"),
    ("How to make money online fast", "money"),
    ("I am broke what should I do", "money"),
    ("How do I start earning", "money"),
    ("Best ways to earn from coding", "money"),
    ("How to get rich from nothing", "money"),
    ("Ideas for passive income streams", "money"),
    ("How to earn money from YouTube", "money"),
    ("Can I make money freelancing", "money"),
    ("I want to build wealth", "money"),
    ("How to save money as a student", "money"),
    ("How to double my income", "money"),
    ("Ways to earn money from home", "money"),
    ("How to make money without a job", "money"),
    ("I want financial independence", "money"),
    ("How to invest small amounts", "money"),
    ("How to start a side hustle", "money"),
    ("Earn money using AI tools", "money"),
    ("How do people make millions", "money"),
    ("Is dropshipping profitable", "money"),
    ("How to monetize my skills", "money"),
    ("How to earn money in India", "money"),
    ("I want to escape poverty", "money"),
    ("Best online jobs for beginners", "money"),
    ("How to earn money with no skills", "money"),
    ("Ways to make quick cash", "money"),
    ("How to grow my income streams", "money"),
    ("Teach me money making strategies", "money"),
    ("I feel lazy and unproductive", "motivation"),
    ("Give me a reason to work hard", "motivation"),
    ("I don't feel like doing anything", "motivation"),
    ("How to stop procrastinating", "motivation"),
    ("I have no motivation to study", "motivation"),
    ("Push me to achieve my goals", "motivation"),
    ("I keep wasting time", "motivation"),
    ("How to stay consistent daily", "motivation"),
    ("I feel like quitting everything", "motivation"),
    ("How to build discipline", "motivation"),
    ("I am tired but I need to work", "motivation"),
    ("Motivate me to code today", "motivation"),
    ("How to stop being distracted", "motivation"),
    ("I can't focus on my work", "motivation"),
    ("How to stay productive all day", "motivation"),
    ("I need energy to keep going", "motivation"),
    ("How to stay committed", "motivation"),
    ("Why am I so lazy", "motivation"),
    ("Help me stay on track", "motivation"),
    ("I want to improve my habits", "motivation"),
    ("How to push through hard times", "motivation"),
    ("I feel stuck in life", "motivation"),
    ("How to overcome failure", "motivation"),
    ("I want to become better", "motivation"),
    ("How to stay driven", "motivation"),
    ("I need a productivity boost", "motivation"),
    ("I keep delaying my work", "motivation"),
    ("Help me stay focused", "motivation"),
    ("How to avoid distractions", "motivation"),
    ("I want to achieve my dreams", "motivation"),
    ("I feel very sad", "healing"),
    ("I am emotionally hurt", "healing"),
    ("How to heal from heartbreak", "healing"),
    ("I feel lonely and empty", "healing"),
    ("How to deal with anxiety", "healing"),
    ("I am stressed all the time", "healing"),
    ("I keep overthinking everything", "healing"),
    ("How to calm my mind", "healing"),
    ("I feel broken inside", "healing"),
    ("How to heal emotionally", "healing"),
    ("I feel lost in life", "healing"),
    ("How to recover from pain", "healing"),
    ("I feel depressed", "healing"),
    ("How to stop negative thoughts", "healing"),
    ("I feel like no one understands me", "healing"),
    ("I am mentally exhausted", "healing"),
    ("How to find inner peace", "healing"),
    ("I feel hopeless", "healing"),
    ("How to deal with emotional pain", "healing"),
    ("I feel insecure", "healing"),
    ("How to heal from past trauma", "healing"),
    ("I feel overwhelmed", "healing"),
    ("How to stop feeling anxious", "healing"),
    ("I feel worthless", "healing"),
    ("How to handle loneliness", "healing"),
    ("I feel disconnected from myself", "healing"),
    ("How to reduce stress", "healing"),
    ("I feel drained emotionally", "healing"),
    ("How to feel better mentally", "healing"),
    ("I need emotional support", "healing"),
    ("I want to connect with God", "god"),
    ("How to pray to God", "god"),
    ("Teach me about faith", "god"),
    ("I want spiritual guidance", "god"),
    ("How to trust God completely", "god"),
    ("I feel far from God", "god"),
    ("How to build strong faith", "god"),
    ("What does God want from me", "god"),
    ("How to grow spiritually", "god"),
    ("I want to understand God", "god"),
    ("How to hear God's voice", "god"),
    ("I need God's help", "god"),
    ("How to strengthen my belief", "god"),
    ("I want to follow God", "god"),
    ("Guide me in my spiritual path", "god"),
    ("How to become closer to God", "god"),
    ("I feel disconnected spiritually", "god"),
    ("How to trust divine plan", "god"),
    ("I want peace through God", "god"),
    ("Teach me to pray better", "god"),
    ("How to increase my faith", "god"),
    ("I need spiritual strength", "god"),
    ("How to live a godly life", "god"),
    ("I want God's guidance", "god"),
    ("Help me understand spirituality", "god"),
    ("How to surrender to God", "god"),
    ("I want divine connection", "god"),
    ("How to follow God's will", "god"),
    ("I feel lost without God", "god"),
    ("Show me spiritual direction", "god")
]
    return data